SC-7700 - Updating Merlin's group (states, counties) names to official
hpi-schul-cloud/oeh-search-etl pull request #14
Opened 2020-11-10 12:47 UTC by JohnKoumarelas

# Description
County (Kreis) codes are now converted to the official format, being prefixed with "3".

Extra things that are done:
* Merlin variable names converted to English
* Prepared proper state group values to be used in the future.
* Extra code refinements.
* Added mds_oeh_override.xml, so we can search using the groups field (ccm:ph_invited).
* Changes in the Dockerfile to support the new mds_oeh_override.xml

## Links to Tickets or other pull requests
https://ticketsystem.hpi-schul-cloud.org/browse/SC-7700

## Changes

1. Fixes an issue with county (Kreis) IDs.
2. Provides an additional way to filter content in terms of their visibility (permissions).

## Datasecurity <sub><sup>details [on Confluence](https://docs.schul-cloud.org/x/2S3GBg)</sup></sub>
No changes.

## Deployment

## New Repos, NPM pakages or vendor scripts

## Screenshots of UI changes

## Approval for review

- [ ] All points were discussed with the ticket creator, support-team or product owner. The code upholds all quality guidelines from the PR-template.

> Notice: Please remove the WIP label if the PR is ready to review, otherwise nobody will review it.

### Link to Definiton of Done

More and detailed information on the _definition of done_ can be found [on Confluence](https://docs.schul-cloud.org/pages/viewpage.action?pageId=92831762)

2020-11-10 16:58 UTC, virgilchiriac approved these changes

2020-11-13 10:38 UTC, JenyMzo approved these changes

2020-11-14 13:32 UTC, virgilchiriac requested changes

2020-11-14 13:32 UTC, virgilchiriac commented on schulcloud/metadatasets/mds_oeh_override.xml
> +		<query join="AND" id="ngsearch">
should be OR, otherwise we are not getting any other results

2020-11-14 13:32 UTC, virgilchiriac commented on schulcloud/metadatasets/mds_oeh_override.xml
> +		<query join="AND" id="ngsearch">
should be OR

2020-11-16 09:50 UTC, virgilchiriac approved these changes

2020-11-16 09:51 UTC, susannegernandt approved these changes

2020-11-16 09:51 UTC, merged